local-settings:
  user-workflow:
    workflow-name: pay-per-thought
  workflow-artifacts:
    workflow-path: .
    config-path: ./config.dev.json
    secrets-path: ""
  rpcs:
    - chain-name: ethereum-testnet-sepolia-arbitrum-1
      url: https://arbitrum-sepolia-rpc.publicnode.com
