name: pay-per-thought-workflow
version: "2.1.0"

trigger:
  type: webhook
  config:
    method: POST
    path: /api/research
    schema:
      type: object
      required: [query, max_budget_usd]
      properties:
        query: { type: string, minLength: 5 }
        max_budget_usd: { type: number, minimum: 0.01 }

nodes:
  # 1. SETUP: Generate session ID and pre-calculate hashes/costs
  - id: setup_node
    type: custom_compute
    description: "Initialize session and pre-calculate EVM parameters"
    inputs:
      query: "$(trigger.body.query)"
      max_budget_usd: "$(trigger.body.max_budget_usd)"
    config:
      runtime: python
      handler: agent/cre_adapter.py
      entry_point: setup_workflow
    outputs:
      session_id: { type: string }
      session_bytes: { type: string }
      step_1_id: { type: string }
      step_1_bytes: { type: string }
      step_1_cost_wei: { type: string }
      step_1_description: { type: string }
      step_1_tool: { type: string }
      step_2_id: { type: string }
      step_2_bytes: { type: string }
      step_2_cost_wei: { type: string }
      step_2_description: { type: string }
      step_2_tool: { type: string }
      total_cost_usd: { type: number }
      total_cost_wei: { type: string }
      step_count: { type: integer }

  # 2. BUDGET LOCK (x402)
  - id: budget_lock_node
    type: evm_write
    description: "Lock total budget in x402 contract"
    depends_on: [setup_node]
    inputs:
      contract_address: "$(secrets.X402_CONTRACT_ADDRESS)"
      chain: "ethereum-testnet-sepolia"
      method: "lockBudget(bytes32,uint256,uint256)"
      args:
        - "$(setup_node.outputs.session_bytes)"
        - "$(setup_node.outputs.total_cost_wei)"
        - "$(setup_node.outputs.step_count)"
    config:
      gas_limit: 500000
    outputs:
      tx_hash: { type: string }
  
  # 3. STEP 1: AUTH
  - id: step_1_auth
    type: evm_write
    description: "Authorize Step 1 payment"
    depends_on: [budget_lock_node]
    inputs:
      contract_address: "$(secrets.X402_CONTRACT_ADDRESS)"
      chain: "ethereum-testnet-sepolia"
      method: "authorizePayment(bytes32,bytes32,uint256)"
      args:
        - "$(setup_node.outputs.session_bytes)"
        - "$(setup_node.outputs.step_1_bytes)"
        - "$(setup_node.outputs.step_1_cost_wei)"
    config:
      gas_limit: 200000
    outputs:
      tx_hash: { type: string }

  # 4. STEP 1: EXECUTE
  - id: step_1_execute
    type: custom_compute
    description: "Execute Step 1 (Dynamic Tool)"
    depends_on: [step_1_auth]
    inputs:
      query: "$(trigger.body.query)"
      step_tool: "$(setup_node.outputs.step_1_tool)"
      step_description: "$(setup_node.outputs.step_1_description)"
    config:
      runtime: python
      handler: agent/cre_adapter.py
      entry_point: execute_step_with_query_adapter
      secrets: [TAVILY_API_KEY, GEMINI_API_KEY]
    outputs:
      output: { type: object }
      sources: { type: array }
      tool: { type: string }
  
  # 5. STEP 1: CONFIRM (x402)
  - id: step_1_confirm
    type: evm_write
    description: "Confirm Step 1 completion"
    depends_on: [step_1_execute]
    inputs:
      contract_address: "$(secrets.X402_CONTRACT_ADDRESS)"
      chain: "ethereum-testnet-sepolia"
      method: "confirmExecution(bytes32,bytes32)"
      args:
        - "$(setup_node.outputs.session_bytes)"
        - "$(setup_node.outputs.step_1_bytes)"
    config:
      gas_limit: 200000

  # 6. STEP 2: AUTH
  - id: step_2_auth
    type: evm_write
    description: "Authorize Step 2 payment"
    depends_on: [step_1_confirm]
    inputs:
      contract_address: "$(secrets.X402_CONTRACT_ADDRESS)"
      chain: "ethereum-testnet-sepolia"
      method: "authorizePayment(bytes32,bytes32,uint256)"
      args:
        - "$(setup_node.outputs.session_bytes)"
        - "$(setup_node.outputs.step_2_bytes)"
        - "$(setup_node.outputs.step_2_cost_wei)"
    config:
      gas_limit: 200000

  # 7. STEP 2: EXECUTE
  - id: step_2_execute
    type: custom_compute
    description: "Execute Step 2 (Dynamic Tool)"
    depends_on: [step_2_auth]
    inputs:
      query: "$(trigger.body.query)"
      step_tool: "$(setup_node.outputs.step_2_tool)"
      step_description: "$(setup_node.outputs.step_2_description)"
      prior_result: "$(step_1_execute.outputs)"
    config:
      runtime: python
      handler: agent/cre_adapter.py
      entry_point: execute_step_with_query_adapter
      secrets: [TAVILY_API_KEY, GEMINI_API_KEY]
    outputs:
      output: { type: object }
      sources: { type: array }
      tool: { type: string }

  # 8. STEP 2: CONFIRM (x402)
  - id: step_2_confirm
    type: evm_write
    description: "Confirm Step 2 completion"
    depends_on: [step_2_execute]
    inputs:
      contract_address: "$(secrets.X402_CONTRACT_ADDRESS)"
      chain: "ethereum-testnet-sepolia"
      method: "confirmExecution(bytes32,bytes32)"
      args:
        - "$(setup_node.outputs.session_bytes)"
        - "$(setup_node.outputs.step_2_bytes)"
    config:
      gas_limit: 200000

  # 9. SYNTHESIS
  - id: synthesis_node
    type: custom_compute
    description: "Synthesize final answer"
    depends_on: [step_2_confirm]
    inputs:
      query: "$(trigger.body.query)"
      step_1_result: "$(step_1_execute.outputs)"
      step_2_result: "$(step_2_execute.outputs)"
      total_cost: "$(setup_node.outputs.total_cost_usd)"
    config:
      runtime: python
      handler: agent/cre_adapter.py
      entry_point: synthesize_adapter
      secrets: [GEMINI_API_KEY]
    outputs:
      answer: { type: string }
      confidence: { type: string }
  
  # 10. SETTLEMENT
  - id: settlement_node
    type: evm_write
    description: "Settle unused budget"
    depends_on: [synthesis_node]
    inputs:
      contract_address: "$(secrets.X402_CONTRACT_ADDRESS)"
      chain: "ethereum-testnet-sepolia"
      # Assuming total spent matches total cost for this fixed demo
      method: "settleBudget(bytes32,uint256)"
      args:
        - "$(setup_node.outputs.session_bytes)"
        - "$(setup_node.outputs.total_cost_wei)" 
    config:
      gas_limit: 200000

secrets:
  - TAVILY_API_KEY
  - GEMINI_API_KEY
  - PRIVATE_KEY
  - X402_CONTRACT_ADDRESS
  - RPC_URL

capabilities:
  - custom_compute
  - evm_write
